import React from 'react';
import { act, create } from 'react-test-renderer';
import { TextInput } from 'react-native';
import { PhoneAuthScreen } from './phone-auth-screen';
import { MarketSelector } from './market-selector';
import { sendPhoneVerificationCode } from '@/lib/api';
import { getTrustedCustomer, restoreTrustedCustomerSession } from '@/lib/auth-token';
const mockRouter = { push: jest.fn(), replace: jest.fn() };
jest.mock('expo-router', () => ({ useRouter: () => mockRouter, Redirect: () => null }));
jest.mock('react-i18next', () => ({ useTranslation: () => ({ t: key => key }) }));
jest.mock('@/components/market-selector', () => ({ MarketSelector: () => null }));
jest.mock('@/components/country-picker', () => ({ CountryPicker: () => null }));
jest.mock('@/components/tracking-ui', () => ({ clientTheme: {} }));
jest.mock('@/lib/api', () => ({ sendPhoneVerificationCode: jest.fn() }));
jest.mock('@/lib/auth-token', () => ({ getTrustedCustomer: jest.fn(), restoreTrustedCustomerSession: jest.fn(), useAuthSession: () => ({ status: 'unauthenticated' }) }));
jest.mock('@/notifications/registerPushNotifications', () => ({ registerCustomerPushNotifications: jest.fn() }));
jest.mock('@/localization/provider', () => ({ useAppLanguage: () => ({ hasSavedLanguage: true, isRTL: false }) }));
jest.mock('@/hooks/use-android-keyboard-inset', () => ({ useAndroidKeyboardInset: () => 0 }));
let tree;
beforeEach(() => { jest.clearAllMocks(); getTrustedCustomer.mockResolvedValue(null); });
afterEach(async () => { if (tree) await act(async () => tree.unmount()); tree = null; });
it('logs in without a market selector and omits market from OTP navigation', async () => {
  await act(async () => { tree = create(<PhoneAuthScreen mode="login" />); });
  expect(tree.root.findAllByType(MarketSelector)).toHaveLength(0);
  const phone = () => tree.root.findByType(TextInput);
  await act(async () => phone().props.onChangeText('70123456'));
  await act(async () => phone().props.onSubmitEditing());
  expect(sendPhoneVerificationCode).toHaveBeenCalledWith('+96170123456', undefined);
  expect(mockRouter.push).toHaveBeenCalledWith({ pathname: '/verify-phone', params: { phoneNumber: '+96170123456' } });
});
it('requires a market during registration and preserves it through OTP navigation', async () => {
  await act(async () => { tree = create(<PhoneAuthScreen mode="register" />); });
  const phone = () => tree.root.findByType(TextInput);
  await act(async () => phone().props.onChangeText('70123456'));
  await act(async () => phone().props.onSubmitEditing());
  expect(sendPhoneVerificationCode).not.toHaveBeenCalled();
  await act(async () => tree.root.findByType(MarketSelector).props.onChange('CH'));
  await act(async () => tree.root.findAll(node => node.props.accessibilityRole === 'checkbox' && typeof node.props.onPress === 'function')[0].props.onPress());
  await act(async () => phone().props.onSubmitEditing());
  expect(sendPhoneVerificationCode).toHaveBeenCalledWith('+96170123456', 'CH');
  expect(mockRouter.push).toHaveBeenCalledWith({ pathname: '/verify-phone', params: { phoneNumber: '+96170123456', marketCode: 'CH' } });
});
it('restores a trusted account without choosing a market', async () => {
  getTrustedCustomer.mockResolvedValue({ phoneNumber: '+96170123456' });
  restoreTrustedCustomerSession.mockResolvedValue({ status: 'restored' });
  await act(async () => { tree = create(<PhoneAuthScreen mode="login" />); });
  await act(async () => tree.root.findAll(node => node.props.accessibilityRole === 'button' && typeof node.props.onPress === 'function')[0].props.onPress());
  expect(restoreTrustedCustomerSession).toHaveBeenCalledWith();
});
jest.mock('@/localization/i18n', () => ({ __esModule: true, default: { t: value => value } }));
