import React from 'react';
import { act, create } from 'react-test-renderer';
import { afterEach, expect, it, jest } from '@jest/globals';
import VehicleRequestRoute from '@/app/vehicle-request';
import { AddressEditor } from './address-editor';
import { ScheduleEditor } from './schedule-editor';
import { newVehicleDraft } from './vehicle-draft';
import { readVehicleDraft, writeVehicleDraft } from './vehicle-draft-storage';
import { getDrivingDistance } from '@/lib/places';
jest.mock('expo-router', () => ({ Stack: { Screen: () => null }, useLocalSearchParams: () => ({ serviceId: 'service' }), useRouter: () => ({ back: jest.fn() }) }));
jest.mock('react-i18next', () => ({ useTranslation: () => ({ t: key => key, i18n: { dir: () => 'ltr', language: 'en' } }) }));
jest.mock('react-native-safe-area-context', () => ({ SafeAreaView: 'SafeAreaView', useSafeAreaInsets: () => ({ bottom: 0 }) }));
jest.mock('@/lib/auth-token', () => ({ useAuthSession: () => ({ user: { id: 'owner', countryCode: 'DE' } }) }));
jest.mock('@/lib/places', () => ({ getDrivingDistance: jest.fn(async () => 27) }));
jest.mock('./service-header', () => ({ ServiceHeader: () => null }));
jest.mock('./submit-vehicle-draft', () => ({ submitVehicleDraft: jest.fn() }));
jest.mock('./address-editor', () => ({ AddressEditor: () => null }));
jest.mock('./schedule-editor', () => ({ ScheduleEditor: () => null, scheduleLabel: () => '' }));
jest.mock('./vehicle-editor', () => ({ VehicleEditor: () => null }));
jest.mock('./vehicle-draft-storage', () => ({ readVehicleDraft: jest.fn(), writeVehicleDraft: jest.fn() }));
jest.mock('./vehicle-draft', () => ({ ...jest.requireActual('./vehicle-draft'), validateVehicleDraft: () => [] }));
let tree;
afterEach(async () => { if (tree) await act(async () => tree.unmount()); });
it.each([true, false])('fills the vehicle pair, preserves its details and only advances on confirmation (%s)', async confirmed => {
  jest.clearAllMocks();
  const original = newVehicleDraft('owner', 'service');
  original.vehicle.brand = 'Current vehicle';
  original.condition.notes = 'Current notes';
  readVehicleDraft.mockReturnValue(original);
  await act(async () => { tree = create(<VehicleRequestRoute />); });
  const next = () => tree.root.findAll(node => node.props.accessibilityRole === 'button' && typeof node.props.onPress === 'function').find(node => node.findAll(child => child.props.children === 'vehicleRequest.continue').length);
  await act(async () => next().props.onPress());
  await act(async () => next().props.onPress());
  const route = { pickup: { latitude: 48, longitude: 8, address: 'Warehouse' }, dropoff: { latitude: 49, longitude: 9, address: 'Shop' } };
  await act(async () => tree.root.findByType(AddressEditor).props.onRepeatRoute(route, confirmed));
  expect(getDrivingDistance).toHaveBeenCalledWith(route.pickup, route.dropoff, expect.anything());
  const latest = writeVehicleDraft.mock.calls.at(-1)[0];
  expect(latest).toMatchObject({ ...route, vehicle: original.vehicle, condition: original.condition, schedule: original.schedule, distanceKm: 27 });
  if (confirmed) expect(tree.root.findByType(ScheduleEditor)).toBeDefined();
  else expect(tree.root.findByType(AddressEditor).props.value).toEqual(route.pickup);
});
